### ISSUE TITLE
误杀

### ISSUE THREAD

**Issue by Karmylr** [Potterli20/hosts#3]
![image](https://user-images.githubusercontent.com/69903376/151514572-be69c9a7-fa0c-4d33-b59e-b1c534aad31d.png)
为什么abp也屏蔽...

**Comment by Karmylr** [comment]
还有getadblock.com

**Comment by Potterli20** [comment]
> 

更新你的规则

**Comment by Potterli20** [comment]
![Screenshot_2022-01-28-16-41-21-876_com android browser](https://user-images.githubusercontent.com/28734349/151514952-3bb5dfb7-2e92-4de4-97d9-6ad5dacd365f.jpg)

**Comment by Karmylr** [comment]
群里的ad-domains.txt有
