### ISSUE TITLE
规则错误

### ISSUE THREAD

**Issue by Miroxyz** [Potterli20/hosts#7]
YouTuBe 去广告规则列表里这两个域名规则多了两条 . 结尾的记录，导致 clash for android 导入失败

```
  - '+.r4---sn-o097znss.googlevideo.com'
  - '+.r4---sn-o097znss.googlevideo.com.'
  
  - '+.rr4---sn-jvhj5nu-nh4l.googlevideo.com'
  - '+.rr4---sn-jvhj5nu-nh4l.googlevideo.com.'
```

**Comment by Potterli20** [comment]
> YouTuBe 去广告规则列表里这两个域名规则多了两条 . 结尾的记录，导致 clash for android 导入失败
> 
> ```
>   - '+.r4---sn-o097znss.googlevideo.com'
>   - '+.r4---sn-o097znss.googlevideo.com.'
>   
>   - '+.rr4---sn-jvhj5nu-nh4l.googlevideo.com'
>   - '+.rr4---sn-jvhj5nu-nh4l.googlevideo.com.'
> ```

你是用pre还是原版的clash？

**Comment by Miroxyz** [comment]
pre 版的

**Comment by Potterli20** [comment]
> pre 版的

我测试一下

**Comment by Potterli20** [comment]
> pre 版的

你有配置文件？

**Comment by Potterli20** [comment]
规则是修了，你看看还有问题不
